name: Java CI with ExtentReports and Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11 and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          maven-version: '3.8.1'

      - name: Configure Git
        run: |
          git config --global user.email "smtab142790@gmail.com"
          git config --global user.name "SmtOzcelik"

      - name: Build with Maven
        run: mvn -B clean install

      - name: Run Tests and Generate ExtentReports
        run: mvn test

      - name: Archive ExtentReports
        uses: actions/upload-artifact@v2
        with:
          name: extent-reports
          path: raporlar

      - name: Set up Docker
        uses: actions/setup-java@v2
        with:
          distribution: 'docker'
          java-version: '11'

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/githubactionpushed:latest .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker push ${{ secrets.DOCKER_USERNAME }}/githubactionpushed:latest

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11 and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          maven-version: '3.8.1'

      - name: Configure Git
        run: |
          git config --global user.email "smtab142790@gmail.com"
          git config --global user.name "SmtOzcelik"

      - name: Download ExtentReports
        uses: actions/download-artifact@v2
        with:
          name: extent-reports
          path: raporlar

      - name: Publish to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          GITHUB_TOKEN: ${{ secrets.TOKENN }}
          BRANCH: gh-pages
          FOLDER: raporlar
