name: Java CI with ExtentReports

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11 and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven
      - uses: browser-actions/setup-chrome@latest
      - run: |
          chmod +x ./scripts/InstallChrome.sh
                     ./scripts/InstallChrome.sh 

      - name: Configure Git
        run: |
          git config --global user.email "smtab142790@gmail.com"
          git config --global user.name "SmtOzcelik"

      - name: Build with Maven
        run: mvn test --file pom.xml

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run Tests and Generate ExtentReports
        run: mvn -B test

      - name: Archive ExtentReports
        uses: actions/upload-artifact@v2
        with:
          name: extent-reports
          path: raporlar
  docker:
    name: Build and Deploy Spring Boot App
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'corretto'
          cache: 'maven'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Configure Git
        run: |
          git config --global user.email "smtab142790@gmail.com"
          git config --global user.name "SmtOzcelik"

      - name: Download ExtentReports
        uses: actions/download-artifact@v2
        with:
          name: extent-reports
          path: raporlar

      - name: Build App
        run: mvn -B package --file pom.xml -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Bulid and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/githubactionpushed:latest







  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11 and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          maven-version: '3.8.1'

      - name: Configure Git
        run: |
          git config --global user.email "smtab142790@gmail.com"
          git config --global user.name "SmtOzcelik"

      - name: Download ExtentReports
        uses: actions/download-artifact@v2
        with:
          name: extent-reports
          path: raporlar

      - name: Publish to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          GITHUB_TOKEN: ${{ secrets.TOKENN }}
          BRANCH: gh-pages
          FOLDER: raporlar
